version: "3"
services:
  node:
    image: node:15-alpine3.10
    volumes:
      - .:/app
    working_dir: /app
    command: npx next dev
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    ports:
    - 3000:3000
  db:
    image: mariadb:10.5.9
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_DATABASE: senscritique
    volumes:
      - .data/mysql:/var/lib/mysql
  python:
    build:
      context: docker/python
      dockerfile: Dockerfile
    env_file:
      - .env
    working_dir: /app
    volumes:
    - .:/app

